Rewrite Hurricano.
HurricanoBot/Hurricano pull request #46
Opened 2021-08-07 13:51 UTC by Dragonizedpizza

This PR rewrites Hurricano, with the following changes.

* Upgrades to the official v13 release.
* Prepares it for Node.js v16.
* Fixes all bugs.
* Makes code ESLint compliant.
* Adds more commands, and shifts to interactions.
* Uses JSDoc on more things.
* ~~Fixes Militia's shitty code.~~

This PR is not ready as of now, anyone is free to contribute.

2021-08-10 12:39 UTC, achaljhawar requested changes
compare and fetch your branch with the main branch

2021-08-11 03:59 UTC, achaljhawar approved these changes

2021-08-17 10:06 UTC, xHeaveny approved these changes

2021-08-17 10:18 UTC, Dragonizedpizza commented
its not done yet though

2022-02-09 08:08 UTC, closed without merging